version: "3"
services:
  web:
    image: nginx
    links:
     - api
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
     - ~/.secret:/etc/certs
    ports:
     - "443:443"
  api:
    image: rlkamradt/express:latest
    env_file: ~/.secret/secrets.env
    ports:
     - "3000:3000"
